contentColumnType: text
fieldGroup: a2d83bec-ca3d-459e-af81-1d44cfb17e7c
handle: testimonialSource
instructions: ''
name: 'Testimonial Source'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
